In [162]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [163]:
data = pd.read_csv("d:\\UAH GO CHARGERS\\Spring 26\\MSC450\\Module 5\\Assignment 4\\Auto.csv")
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,name
0,18.0,8,307.0,130,3504,12.0,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,ford torino

In [164]:
#model 1

In [165]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
displacement = poly.fit_transform(data.iloc[:,2:3])
displacement = pd.DataFrame(displacement[:,1:], columns = ['displacement1','displacement2'])
horsepower = poly.fit_transform(data.iloc[:,3:4])
horsepower = pd.DataFrame(horsepower[:,1:], columns = ["horsepower1", "horsepower2"])
weight = poly.fit_transform(data.iloc[:,4:5])
weight = pd.DataFrame(weight[:,1:], columns = ["weight1", "weight2"])
data1 = pd.concat([data.iloc[:,0:2],displacement, horsepower, weight, data.iloc[:,5:6]], axis = 1)
data1

,mpg,cylinders,displacement1,displacement2,horsepower1,horsepower2,weight1,weight2,acceleration
0,18.0,8,307.0,94249.0,130.0,16900.0,3504.0,12278016.0,12.0
1,15.0,8,350.0,122500.0,165.0,27225.0,3693.0,13638249.0,11.5
2,18.0,8,318.0,101124.0,150.0,22500.0,3436.0,11806096.0,11.0
3,16.0,8,304.0,92416.0,150.0,22500.0,3433.0,11785489.0,12.0
4,17.0,8,302.0,91204.0,140.0,19600.0,3449.0,11895601.0,10.5
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,19600.0,86.0,7396.0,2790.0,7784100.0,15.6
388,44.0,4,97.0,9409.0,52.0,2704.0,2130.0,4536900.0,24.6
389,32.0,4,135.0,18225.0,84.0,7056.0,2295.0,5267025.0,11.6
390,28.0,4,120.0,14400.0,79.0,6241.0,2625.0,6890625.0,18.6
391,31.0,4,119.0,14161.0,82.0,6724.0,2720.0,7398400.0,19.4

In [166]:
import statsmodels.api as sm
ols1 = sm.OLS(data1.iloc[:,0], sm.add_constant(data1.iloc[:,1:9]))
lm1 = ols1.fit()
print(lm1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.760
Model:                            OLS   Adj. R-squared:                  0.755
Method:                 Least Squares   F-statistic:                     151.8
Date:                Tue, 17 Feb 2026   Prob (F-statistic):          9.04e-114
Time:                        15:41:44   Log-Likelihood:                -1081.3
No. Observations:                 392   AIC:                             2181.
Df Residuals:                     383   BIC:                             2216.
Df Model:                           8
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
const            62.5637      4.455     14.042      0.000      53.804      71.324
cylinders         0.7847      0.424      1.852      0.065      -0.048       1.618
displacement1    -0.0815      0.024     -3.356      0.001      -0.129      -0.034
displacement2     0.0001   4.35e-05      2.658      0.008    3.01e-05       0.000
horsepower1      -0.2969      0.053     -5.571      0.000      -0.402      -0.192
horsepower2       0.0007      0.000      3.984      0.000       0.000       0.001
weight1          -0.0021      0.003     -0.606      0.545      -0.009       0.005
weight2        9.793e-08   4.58e-07      0.214      0.831   -8.03e-07    9.99e-07
acceleration     -0.3866      0.133     -2.916      0.004      -0.647      -0.126
==============================================================================
Omnibus:                       39.429   Durbin-Watson:                   1.009
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               67.998
Skew:                           0.622   Prob(JB):                     1.72e-15
Kurtosis:                       4.618   Cond. No.                     2.52e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.52e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

In [167]:
#model 2

In [168]:
displacement = np.log(data.iloc[:,2:3])
displacement = displacement.rename(columns={"displacement":"log displacement"})
horsepower = np.log(data.iloc[:,3:4])
horsepower = horsepower.rename(columns={"horsepower":"log_horsepower"})
weight = np.log(data.iloc[:,4:5])
weight = weight.rename(columns={"weight":"log_weight"})
data2 = pd.concat([data.iloc[:,0:2], displacement, horsepower, weight, data.iloc[:,5:6]], axis = 1)
data2

,mpg,cylinders,log displacement,log_horsepower,log_weight,acceleration
0,18.0,8,5.726848,4.867534,8.161660,12.0
1,15.0,8,5.857933,5.105945,8.214194,11.5
2,18.0,8,5.762051,5.010635,8.142063,11.0
3,16.0,8,5.717028,5.010635,8.141190,12.0
4,17.0,8,5.710427,4.941642,8.145840,10.5
...,...,...,...,...,...,...
387,27.0,4,4.941642,4.454347,7.933797,15.6
388,44.0,4,4.574711,3.951244,7.663877,24.6
389,32.0,4,4.905275,4.430817,7.738488,11.6
390,28.0,4,4.787492,4.369448,7.872836,18.6
391,31.0,4,4.779123,4.406719,7.908387,19.4

In [169]:
import statsmodels.api as sm
ols2 = sm.OLS(data2.iloc[:,0], sm.add_constant(data2.iloc[:,1:6]))
lm2 = ols2.fit()
print(lm2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.748
Model:                            OLS   Adj. R-squared:                  0.745
Method:                 Least Squares   F-statistic:                     229.3
Date:                Tue, 17 Feb 2026   Prob (F-statistic):          3.55e-113
Time:                        15:41:44   Log-Likelihood:                -1090.9
No. Observations:                 392   AIC:                             2194.
Df Residuals:                     386   BIC:                             2218.
Df Model:                           5
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const              157.1480     12.362     12.712      0.000     132.843     181.453
cylinders            0.3237      0.355      0.912      0.362      -0.374       1.022
log displacement    -4.2379      1.616     -2.623      0.009      -7.415      -1.061
log_horsepower     -11.2428      1.919     -5.858      0.000     -15.016      -7.469
log_weight          -7.0777      2.759     -2.565      0.011     -12.503      -1.652
acceleration        -0.3750      0.131     -2.868      0.004      -0.632      -0.118
==============================================================================
Omnibus:                       39.957   Durbin-Watson:                   0.974
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               62.427
Skew:                           0.667   Prob(JB):                     2.78e-14
Kurtosis:                       4.430   Cond. No.                     1.25e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.25e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [170]:
#model 3

In [171]:
mpg = np.log(data.iloc[:,0:1])
mpg = mpg.rename(columns={"mpg":"log_mpg"})
data3 = pd.concat([mpg,data.iloc[:,1:6]], axis = 1)
data3

      log_mpg  cylinders  displacement  horsepower  weight  acceleration
0    2.890372          8         307.0         130    3504          12.0
1    2.708050          8         350.0         165    3693          11.5
2    2.890372          8         318.0         150    3436          11.0
3    2.772589          8         304.0         150    3433          12.0
4    2.833213          8         302.0         140    3449          10.5
..        ...        ...           ...         ...     ...           ...
387  3.295837          4         140.0          86    2790          15.6
388  3.784190          4          97.0          52    2130          24.6
389  3.465736          4         135.0          84    2295          11.6
390  3.332205          4         120.0          79    2625          18.6
391  3.433987          4         119.0          82    2720          19.4

[392 rows x 6 columns]

In [172]:
import statsmodels.api as sm
ols3 = sm.OLS(data3.iloc[:,0],sm.add_constant(data3.iloc[:,1:6]))
lm3 = ols3.fit()
print(lm3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                log_mpg   R-squared:                       0.791
Model:                            OLS   Adj. R-squared:                  0.789
Method:                 Least Squares   F-statistic:                     292.9
Date:                Tue, 17 Feb 2026   Prob (F-statistic):          6.18e-129
Time:                        15:41:44   Log-Likelihood:                 174.31
No. Observations:                 392   AIC:                            -336.6
Df Residuals:                     386   BIC:                            -312.8
Df Model:                           5
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            4.2203      0.098     42.956      0.000       4.027       4.413
cylinders       -0.0260      0.015     -1.718      0.087      -0.056       0.004
displacement -1.803e-05      0.000     -0.054      0.957      -0.001       0.001
horsepower      -0.0028      0.001     -4.513      0.000      -0.004      -0.002
weight          -0.0002   3.01e-05     -6.687      0.000      -0.000      -0.000
acceleration    -0.0057      0.005     -1.235      0.218      -0.015       0.003
==============================================================================
Omnibus:                        5.326   Durbin-Watson:                   0.890
Prob(Omnibus):                  0.070   Jarque-Bera (JB):                5.251
Skew:                           0.223   Prob(JB):                       0.0724
Kurtosis:                       3.351   Cond. No.                     3.87e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 3.87e+04. This might indicate that there are
strong multicollinearity or other numerical problems.

In [173]:
#model 4

In [174]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2)
mpg = np.log(data.iloc[:,0:1])
mpg = mpg.rename(columns={"mpg":"log_mpg"})
displacement = np.log(data.iloc[:,2:3])
displacement = displacement.rename(columns={"displacement":"log_displacement"})
horsepower = np.log(data.iloc[:,3:4])
horsepower = horsepower.rename(columns={"horsepower":"log_horsepower"})
weight = np.log(data.iloc[:,4:5])
weight = weight.rename(columns={"weight":"log_weight"})
data4 = pd.concat([mpg,data.iloc[:,1:2],displacement, horsepower, weight, data.iloc[:,5:6]], axis = 1)
data4

,log_mpg,cylinders,log_displacement,log_horsepower,log_weight,acceleration
0,2.890372,8,5.726848,4.867534,8.161660,12.0
1,2.708050,8,5.857933,5.105945,8.214194,11.5
2,2.890372,8,5.762051,5.010635,8.142063,11.0
3,2.772589,8,5.717028,5.010635,8.141190,12.0
4,2.833213,8,5.710427,4.941642,8.145840,10.5
...,...,...,...,...,...,...
387,3.295837,4,4.941642,4.454347,7.933797,15.6
388,3.784190,4,4.574711,3.951244,7.663877,24.6
389,3.465736,4,4.905275,4.430817,7.738488,11.6
390,3.332205,4,4.787492,4.369448,7.872836,18.6
391,3.433987,4,4.779123,4.406719,7.908387,19.4

In [175]:
import statsmodels.api as sm
ols4 = sm.OLS(data4.iloc[:,0], sm.add_constant(data4.iloc[:,1:6]))
lm4 = ols4.fit()
print(lm4.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                log_mpg   R-squared:                       0.805
Model:                            OLS   Adj. R-squared:                  0.803
Method:                 Least Squares   F-statistic:                     319.0
Date:                Tue, 17 Feb 2026   Prob (F-statistic):          1.20e-134
Time:                        15:41:44   Log-Likelihood:                 187.69
No. Observations:                 392   AIC:                            -363.4
Df Residuals:                     386   BIC:                            -339.6
Df Model:                           5
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const                8.7657      0.474     18.505      0.000       7.834       9.697
cylinders           -0.0206      0.014     -1.515      0.131      -0.047       0.006
log_displacement    -0.0901      0.062     -1.455      0.146      -0.212       0.032
log_horsepower      -0.4844      0.074     -6.588      0.000      -0.629      -0.340
log_weight          -0.3303      0.106     -3.123      0.002      -0.538      -0.122
acceleration        -0.0155      0.005     -3.100      0.002      -0.025      -0.006
==============================================================================
Omnibus:                        9.808   Durbin-Watson:                   0.989
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               12.300
Skew:                           0.245   Prob(JB):                      0.00213
Kurtosis:                       3.717   Cond. No.                     1.25e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.25e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [176]:
displacement = np.log(data.iloc[:,2:3])
displacement = displacement.rename(columns={"displacement":"log_displacement"})
horsepower = np.log(data.iloc[:,3:4])
horsepower = horsepower.rename(columns={"horsepower":"log_horsepower"})
weight = np.log(data.iloc[:,4:5])
weight = weight.rename(columns={"weight":"log_weight"})
data5 = pd.concat([data.iloc[:,0:2],displacement, horsepower, weight, data.iloc[:,5:6]], axis = 1)
data5.head()

    mpg  cylinders  log_displacement  log_horsepower  log_weight  acceleration
0  18.0          8          5.726848        4.867534    8.161660          12.0
1  15.0          8          5.857933        5.105945    8.214194          11.5
2  18.0          8          5.762051        5.010635    8.142063          11.0
3  16.0          8          5.717028        5.010635    8.141190          12.0
4  17.0          8          5.710427        4.941642    8.145840          10.5

In [177]:
import scipy.stats as stats
Z, fit_lambda = stats.boxcox(data5.mpg)
print(fit_lambda)

0.19123084478293514

In [178]:
import statsmodels.api as sm
ols5 = sm.OLS(Z, sm.add_constant(data5.iloc[:,1:6]))
lm5 = ols5.fit()
print(lm5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.798
Model:                            OLS   Adj. R-squared:                  0.795
Method:                 Least Squares   F-statistic:                     305.0
Date:                Tue, 17 Feb 2026   Prob (F-statistic):          1.26e-131
Time:                        15:41:44   Log-Likelihood:                -50.812
No. Observations:                 392   AIC:                             113.6
Df Residuals:                     386   BIC:                             137.5
Df Model:                           5
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const               14.5514      0.870     16.718      0.000      12.840      16.263
cylinders           -0.0254      0.025     -1.017      0.310      -0.075       0.024
log_displacement    -0.1980      0.114     -1.740      0.083      -0.422       0.026
log_horsepower      -0.8730      0.135     -6.461      0.000      -1.139      -0.607
log_weight          -0.5911      0.194     -3.042      0.003      -0.973      -0.209
acceleration        -0.0283      0.009     -3.071      0.002      -0.046      -0.010
==============================================================================
Omnibus:                       13.044   Durbin-Watson:                   0.979
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               16.523
Skew:                           0.313   Prob(JB):                     0.000258
Kurtosis:                       3.787   Cond. No.                     1.25e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.25e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [179]:
#creating a dataframe for constructing all five models

In [180]:
poly = PolynomialFeatures(degree=2)
displacement = poly.fit_transform(data.iloc[:,2:3])
displacement = pd.DataFrame(displacement[:,1:], columns = ['displacement1','displacement2'])
horsepower = poly.fit_transform(data.iloc[:,3:4])
horsepower = pd.DataFrame(horsepower[:,1:], columns = ["horsepower1", "horsepower2"])
weight = poly.fit_transform(data.iloc[:,4:5])
weight = pd.DataFrame(weight[:,1:], columns = ["weight1", "weight2"])

log_displacement = np.log(data.iloc[:,2:3])
log_displacement = log_displacement.rename(columns={"displacement":"log_displacement"})
log_horsepower = np.log(data.iloc[:,3:4])
log_horsepower = log_horsepower.rename(columns={"horsepower":"log_horsepower"})
log_weight = np.log(data.iloc[:,4:5])
log_weight = log_weight.rename(columns={"weight":"log_weight"})
log_mpg = np.log(data.iloc[:,0:1])
log_mpg = log_mpg.rename(columns={"mpg":"log_mpg"})

Z, fit_lambda = stats.boxcox(data5.mpg)
Z = pd.DataFrame(Z, columns=['Z'])

data_new = pd.concat([Z,log_mpg,data.iloc[:,0:2],displacement,horsepower,weight,log_displacement,log_horsepower,log_weight,data.iloc[:,5]], axis = 1)
data_new

,Z,log_mpg,mpg,cylinders,displacement1,displacement2,horsepower1,horsepower2,weight1,weight2,log_displacement,log_horsepower,log_weight,acceleration
0,3.859148,2.890372,18.0,8,307.0,94249.0,130.0,16900.0,3504.0,12278016.0,5.726848,4.867534,8.161660,12.0
1,3.547736,2.708050,15.0,8,350.0,122500.0,165.0,27225.0,3693.0,13638249.0,5.857933,5.105945,8.214194,11.5
2,3.859148,2.890372,18.0,8,318.0,101124.0,150.0,22500.0,3436.0,11806096.0,5.762051,5.010635,8.142063,11.0
3,3.656731,2.772589,16.0,8,304.0,92416.0,150.0,22500.0,3433.0,11785489.0,5.717028,5.010635,8.141190,12.0
4,3.760349,2.833213,17.0,8,302.0,91204.0,140.0,19600.0,3449.0,11895601.0,5.710427,4.941642,8.145840,10.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
387,4.591882,3.295837,27.0,4,140.0,19600.0,86.0,7396.0,2790.0,7784100.0,4.941642,4.454347,7.933797,15.6
388,5.553254,3.784190,44.0,4,97.0,9409.0,52.0,2704.0,2130.0,4536900.0,4.574711,3.951244,7.663877,24.6
389,4.916211,3.465736,32.0,4,135.0,18225.0,84.0,7056.0,2295.0,5267025.0,4.905275,4.430817,7.738488,11.6
390,4.660422,3.332205,28.0,4,120.0,14400.0,79.0,6241.0,2625.0,6890625.0,4.787492,4.369448,7.872836,18.6
391,4.854801,3.433987,31.0,4,119.0,14161.0,82.0,6724.0,2720.0,7398400.0,4.779123,4.406719,7.908387,19.4

In [183]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
error1 = []
error2 = []
error3 = []
error4 = []
error5 = []
for i in range(1,101):
    x = data_new.iloc[:,3:]
    y = data_new.iloc[:,:3]
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

    ols = sm.OLS(y_train[["mpg"]],sm.add_constant(x_train[["cylinders","displacement1","displacement2",
                                                           "horsepower1","horsepower2","weight1","weight2","acceleration"]]))
    lm1 = ols.fit()
    y_pred1 = lm1.predict(sm.add_constant(x_test[["cylinders","displacement1","displacement2","horsepower1",
                                                  "horsepower2","weight1","weight2","acceleration"]]))
    error1.append(mean_squared_error(y_pred1,y_test[["mpg"]]))

    ols = sm.OLS(y_train[["mpg"]], sm.add_constant(x_train[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]]))
    lm2 = ols.fit()
    y_pred2 = lm2.predict(sm.add_constant(x_test[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]]))
    error2.append(mean_squared_error(y_pred2,y_test[["mpg"]]))

    ols = sm.OLS(y_train[["log_mpg"]], sm.add_constant(x_train[["cylinders","displacement1","horsepower1","weight1","acceleration"]]))
    lm3 = ols.fit()
    y_pred3 = np.exp(lm3.predict(sm.add_constant(x_test[["cylinders","displacement1","horsepower1","weight1","acceleration"]])))
    error3.append(mean_squared_error(y_pred3,y_test[["mpg"]]))

    ols = sm.OLS(y_train[["log_mpg"]], sm.add_constant(x_train[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]]))
    lm4 = ols.fit()
    y_pred4 = np.exp(lm4.predict(sm.add_constant(x_test[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]])))
    error4.append(mean_squared_error(y_pred4,y_test[["mpg"]]))

    ols = sm.OLS(y_train[["Z"]], sm.add_constant(x_train[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]]))
    lm5 = ols.fit()
    y_pred5 = (lm5.predict(sm.add_constant(x_test[["cylinders","log_displacement","log_horsepower",
                                                   "log_weight","acceleration"]]))*fit_lambda+1)**(1/fit_lambda)
    error5.append(mean_squared_error(y_pred5,y_test[["mpg"]]))

In [184]:
print(f"Mean of error 1: ",np.mean(error1))
print(f"Mean of error 2: ",np.mean(error2))
print(f"Mean of error 3: ",np.mean(error3))
print(f"Mean of error 4: ",np.mean(error4))
print(f"Mean of error 5: ",np.mean(error5))

Mean of error 1:  14.975602599588123
Mean of error 2:  15.571427391957053
Mean of error 3:  16.142139781937416
Mean of error 4:  15.30627106679999
Mean of error 5:  15.215653002376971

In [189]:
from sklearn.model_selection import KFold
cv = KFold(n_splits = 10, random_state = 1, shuffle = True)
x = data_new.iloc[:,3:]
y = data_new.iloc[:,:3]
error1 = []
error2 = []
error3 = []
error4 = []
error5 = []
for train_index, test_index in cv.split(data_new):
    x_train, x_test = x.iloc[train_index], x.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    ols = sm.OLS(y_train[["mpg"]],sm.add_constant(x_train[["cylinders","displacement1","displacement2",
                                                           "horsepower1","horsepower2","weight1","weight2","acceleration"]]))
    lm1 = ols.fit()
    y_pred1 = lm1.predict(sm.add_constant(x_test[["cylinders","displacement1","displacement2","horsepower1",
                                                  "horsepower2","weight1","weight2","acceleration"]]))
    error1.append(mean_squared_error(y_pred1,y_test[["mpg"]]))

    ols = sm.OLS(y_train[["mpg"]], sm.add_constant(x_train[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]]))
    lm2 = ols.fit()
    y_pred2 = lm2.predict(sm.add_constant(x_test[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]]))
    error2.append(mean_squared_error(y_pred2,y_test[["mpg"]]))

    ols = sm.OLS(y_train[["log_mpg"]], sm.add_constant(x_train[["cylinders","displacement1","horsepower1","weight1","acceleration"]]))
    lm3 = ols.fit()
    y_pred3 = np.exp(lm3.predict(sm.add_constant(x_test[["cylinders","displacement1","horsepower1","weight1","acceleration"]])))
    error3.append(mean_squared_error(y_pred3,y_test[["mpg"]]))

    ols = sm.OLS(y_train[["log_mpg"]], sm.add_constant(x_train[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]]))
    lm4 = ols.fit()
    y_pred4 = np.exp(lm4.predict(sm.add_constant(x_test[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]])))
    error4.append(mean_squared_error(y_pred4,y_test[["mpg"]]))

    ols = sm.OLS(y_train[["Z"]], sm.add_constant(x_train[["cylinders","log_displacement","log_horsepower","log_weight","acceleration"]]))
    lm5 = ols.fit()
    y_pred5 = (lm5.predict(sm.add_constant(x_test[["cylinders","log_displacement","log_horsepower",
                                                   "log_weight","acceleration"]]))*fit_lambda+1)**(1/fit_lambda)
    error5.append(mean_squared_error(y_pred5,y_test[["mpg"]]))

In [190]:
print(f"Mean of error 1: ",np.mean(error1))
print(f"Mean of error 2: ",np.mean(error2))
print(f"Mean of error 3: ",np.mean(error3))
print(f"Mean of error 4: ",np.mean(error4))
print(f"Mean of error 5: ",np.mean(error5))

Mean of error 1:  15.356105769216631
Mean of error 2:  16.022060171181995
Mean of error 3:  16.63868312874107
Mean of error 4:  15.769550358079155
Mean of error 5:  15.67861663763899